package com.zidongxiangxi.pratice.one.dao.master;

import com.zidongxiangxi.pratice.one.dao.annotation.Master;
import com.zidongxiangxi.pratice.one.entity.Text;
import org.apache.ibatis.annotations.Param;

@Master
public interface TextMapper {
    int insert(Text record);

    int insertSelective(Text record);

    Text selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(Text record);

    int updateByPrimaryKey(Text record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") java.util.List<Text> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") java.util.List<Text> list, @Param("selective") Text.Column ... selective);
}